import time
question = input("What is your question? ")
print("Let me think about that...")
time.sleep(10)
print("I don't want to answer that right now.")
time.sleep(2)
print("Hey, here's a question for you!")
time.sleep(1)
input(question + " ")
print("Lol")
